name: Daily Handyman Blogs
on:
  schedule:
    - cron: '0 13 * * *' # 7:00 AM Central Time
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Script
        run: python generate.py
      - name: Commit and Push
        run: |
          git config --global user.name 'Dean-Automator'
          git config --global user.email 'dean@github.com'
          git add .
          git commit -m "Daily Blog Update" || exit 0
          git push

